import { useEffect, useState } from 'react';
import { useNavigate, useLocation } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import api from '../utils/api';

const EmployeeInfo = () => {
  const { user } = useAuth();
  const navigate = useNavigate();
  const location = useLocation();
  const employeeId = location.state?.employeeId;
  const fromRegistration = location.state?.fromRegistration;

  const [formData, setFormData] = useState({
    employeeId: '',
    firstName: '',
    lastName: '',
    email: '',
    phoneNumber: '',
    dateOfBirth: '',
    gender: '',
    address: '',
    department: '',
    position: '',
    hireDate: '',
    salary: ''
  });
  const [profileImage, setProfileImage] = useState(null);
  const [profileImageUrl, setProfileImageUrl] = useState(null);
  const [uploadingImage, setUploadingImage] = useState(false);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  useEffect(() => {
    if (employeeId) {
      fetchEmployee();
    } else if (fromRegistration) {
      // Get current user's employee info
      fetchCurrentEmployee();
    }
  }, [employeeId]);

  const fetchEmployee = async () => {
    try {
      const response = await api.get(`/employees/${employeeId}`);
      const emp = response.data;
      setFormData({
        employeeId: emp.employee_id || '',
        firstName: emp.first_name || '',
        lastName: emp.last_name || '',
        email: emp.email || '',
        phoneNumber: emp.phone_number || '',
        dateOfBirth: emp.date_of_birth || '',
        gender: emp.gender || '',
        address: emp.address || '',
        department: emp.department || '',
        position: emp.position || '',
        hireDate: emp.hire_date || '',
        salary: emp.salary || ''
      });
      setProfileImageUrl(emp.profile_image_url || null);
    } catch (error) {
      console.error('Failed to fetch employee:', error);
    }
  };

  const fetchCurrentEmployee = async () => {
    try {
      const response = await api.get('/auth/me');
      if (response.data.user?.employee) {
        const emp = response.data.user.employee;
        setFormData({
          employeeId: emp.employee_id || '',
          firstName: emp.first_name || '',
          lastName: emp.last_name || '',
          email: emp.email || response.data.user.email || '',
          phoneNumber: emp.phone_number || '',
          dateOfBirth: emp.date_of_birth || '',
          gender: emp.gender || '',
          address: emp.address || '',
          department: emp.department || '',
          position: emp.position || '',
          hireDate: emp.hire_date || '',
          salary: emp.salary || ''
        });
      }
    } catch (error) {
      console.error('Failed to fetch current employee:', error);
    }
  };

  const handleChange = (e) => {
    setFormData({
      ...formData,
      [e.target.name]: e.target.value
    });
  };

  const handleImageChange = (e) => {
    const file = e.target.files[0];
    if (file) {
      setProfileImage(file);
      setProfileImageUrl(URL.createObjectURL(file));
    }
  };

  const handleImageUpload = async () => {
    if (!profileImage || !employeeId) return;

    setUploadingImage(true);
    try {
      const formData = new FormData();
      formData.append('image', profileImage);

      const response = await api.post(`/upload/employee/${employeeId}`, formData, {
        headers: {
          'Content-Type': 'multipart/form-data'
        }
      });

      setProfileImageUrl(response.data.imageUrl);
      setProfileImage(null);
      alert('Profile image uploaded successfully');
    } catch (error) {
      console.error('Failed to upload image:', error);
      alert('Failed to upload image');
    } finally {
      setUploadingImage(false);
    }
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setError('');
    setLoading(true);

    try {
      if (employeeId) {
        await api.put(`/employees/${employeeId}`, {
          ...formData,
          firstName: formData.firstName,
          lastName: formData.lastName,
          phoneNumber: formData.phoneNumber,
          dateOfBirth: formData.dateOfBirth,
          gender: formData.gender,
          address: formData.address,
          department: formData.department,
          position: formData.position,
          hireDate: formData.hireDate,
          salary: formData.salary
        });
      } else {
        // Create new employee (Employee ID will be auto-generated by backend)
        // Build request body, explicitly excluding employeeId
        const requestBody = {
          firstName: formData.firstName,
          lastName: formData.lastName
        };
        
        // Only include optional fields if they have values
        if (formData.email && formData.email.trim() !== '') {
          requestBody.email = formData.email.trim();
        }
        if (formData.phoneNumber && formData.phoneNumber.trim() !== '') {
          requestBody.phoneNumber = formData.phoneNumber.trim();
        }
        if (formData.dateOfBirth) {
          requestBody.dateOfBirth = formData.dateOfBirth;
        }
        if (formData.gender) {
          requestBody.gender = formData.gender;
        }
        if (formData.address && formData.address.trim() !== '') {
          requestBody.address = formData.address.trim();
        }
        if (formData.department) {
          requestBody.department = formData.department;
        }
        if (formData.position) {
          requestBody.position = formData.position;
        }
        if (formData.hireDate) {
          requestBody.hireDate = formData.hireDate;
        }
        if (formData.salary) {
          requestBody.salary = formData.salary;
        }
        
        const response = await api.post('/employees', requestBody);

        // Show Employee ID, Login ID and Password if generated
        const message = `Employee created successfully!\n\nEmployee ID: ${response.data.employee_id || 'N/A'}\nLogin ID: ${response.data.loginId || 'N/A'}\nPassword: ${response.data.password || 'N/A'}\n\nPlease share these credentials with the employee. They must change password on first login.`;
        alert(message);
      }
      navigate('/employees');
    } catch (error) {
      setError(error.response?.data?.error || 'Failed to save employee information');
    } finally {
      setLoading(false);
    }
  };

  const canEditAll = ['Admin', 'HR Officer'].includes(user?.role);

  return (
    <div>
      <h1 className="text-2xl font-bold text-gray-800 mb-6">Employee Information</h1>

      <div className="bg-white rounded-lg shadow-md p-6">
        {error && (
          <div className="bg-red-50 border border-red-200 text-red-700 px-4 py-3 rounded mb-4">
            {error}
          </div>
        )}

        {/* Profile Image Upload */}
        {employeeId && (
          <div className="mb-6 pb-6 border-b">
            <label className="block text-sm font-medium text-gray-700 mb-2">Profile Image</label>
            <div className="flex items-center space-x-4">
              {profileImageUrl ? (
                <img
                  src={profileImageUrl}
                  alt="Profile"
                  className="w-24 h-24 rounded-full object-cover border-2 border-gray-300"
                />
              ) : (
                <div className="w-24 h-24 rounded-full bg-gray-200 flex items-center justify-center">
                  <span className="text-gray-400">No Image</span>
                </div>
              )}
              <div>
                <input
                  type="file"
                  accept="image/*"
                  onChange={handleImageChange}
                  className="mb-2"
                />
                {profileImage && (
                  <button
                    type="button"
                    onClick={handleImageUpload}
                    disabled={uploadingImage}
                    className="bg-purple-600 text-white px-4 py-2 rounded-lg hover:bg-purple-700 disabled:opacity-50 text-sm"
                  >
                    {uploadingImage ? 'Uploading...' : 'Upload Image'}
                  </button>
                )}
              </div>
            </div>
          </div>
        )}

        <form onSubmit={handleSubmit} className="space-y-6">
          <div className="grid grid-cols-2 gap-6">
            {canEditAll && employeeId && (
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">Employee ID</label>
                <input
                  type="text"
                  name="employeeId"
                  value={formData.employeeId}
                  onChange={handleChange}
                  disabled={true}
                  className="w-full px-4 py-2 border border-gray-300 rounded-lg bg-gray-100"
                />
              </div>
            )}
            {canEditAll && !employeeId && (
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">Employee ID</label>
                <input
                  type="text"
                  value="Auto-generated"
                  disabled={true}
                  className="w-full px-4 py-2 border border-gray-300 rounded-lg bg-gray-100 italic text-gray-500"
                />
                <p className="text-xs text-gray-500 mt-1">Employee ID will be automatically generated</p>
              </div>
            )}
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">First Name *</label>
              <input
                type="text"
                name="firstName"
                value={formData.firstName}
                onChange={handleChange}
                required
                className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500"
              />
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">Last Name *</label>
              <input
                type="text"
                name="lastName"
                value={formData.lastName}
                onChange={handleChange}
                required
                className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500"
              />
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">Email</label>
              <input
                type="email"
                name="email"
                value={formData.email}
                onChange={handleChange}
                placeholder="Optional - will auto-generate if empty"
                className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500"
              />
              <p className="text-xs text-gray-500 mt-1">Leave empty to auto-generate email</p>
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">Phone Number</label>
              <input
                type="tel"
                name="phoneNumber"
                value={formData.phoneNumber}
                onChange={handleChange}
                className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500"
              />
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">Date of Birth</label>
              <input
                type="date"
                name="dateOfBirth"
                value={formData.dateOfBirth}
                onChange={handleChange}
                className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500"
              />
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">Gender</label>
              <div className="flex space-x-4">
                <label className="flex items-center">
                  <input
                    type="radio"
                    name="gender"
                    value="Male"
                    checked={formData.gender === 'Male'}
                    onChange={handleChange}
                    className="mr-2"
                  />
                  Male
                </label>
                <label className="flex items-center">
                  <input
                    type="radio"
                    name="gender"
                    value="Female"
                    checked={formData.gender === 'Female'}
                    onChange={handleChange}
                    className="mr-2"
                  />
                  Female
                </label>
                <label className="flex items-center">
                  <input
                    type="radio"
                    name="gender"
                    value="Other"
                    checked={formData.gender === 'Other'}
                    onChange={handleChange}
                    className="mr-2"
                  />
                  Other
                </label>
              </div>
            </div>

            <div className="col-span-2">
              <label className="block text-sm font-medium text-gray-700 mb-2">Address</label>
              <textarea
                name="address"
                value={formData.address}
                onChange={handleChange}
                rows="3"
                className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500"
              />
            </div>

            {canEditAll && (
              <>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">Department</label>
                  <select
                    name="department"
                    value={formData.department}
                    onChange={handleChange}
                    className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500"
                  >
                    <option value="">Select Department</option>
                    <option value="IT">IT</option>
                    <option value="HR">HR</option>
                    <option value="Finance">Finance</option>
                    <option value="Marketing">Marketing</option>
                    <option value="Sales">Sales</option>
                    <option value="Operations">Operations</option>
                  </select>
                </div>

                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">Position</label>
                  <select
                    name="position"
                    value={formData.position}
                    onChange={handleChange}
                    className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500"
                  >
                    <option value="">Select Position</option>
                    <option value="Manager">Manager</option>
                    <option value="Senior Manager">Senior Manager</option>
                    <option value="Director">Director</option>
                    <option value="Executive">Executive</option>
                    <option value="Associate">Associate</option>
                    <option value="Intern">Intern</option>
                  </select>
                </div>

                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">Hire Date</label>
                  <input
                    type="date"
                    name="hireDate"
                    value={formData.hireDate}
                    onChange={handleChange}
                    className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500"
                  />
                </div>

                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">Salary</label>
                  <input
                    type="number"
                    name="salary"
                    value={formData.salary}
                    onChange={handleChange}
                    className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500"
                  />
                </div>
              </>
            )}
          </div>

          <div className="flex justify-end space-x-4">
            <button
              type="button"
              onClick={() => navigate(-1)}
              className="px-6 py-2 border border-gray-300 rounded-lg hover:bg-gray-50"
            >
              Cancel
            </button>
            <button
              type="submit"
              disabled={loading}
              className="px-6 py-2 bg-purple-600 text-white rounded-lg hover:bg-purple-700 disabled:opacity-50"
            >
              {loading ? 'Saving...' : 'Save'}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};

export default EmployeeInfo;

