import { useState, useEffect } from 'react';
import { Link, useNavigate, useLocation } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import api from '../utils/api';

const Login = () => {
  const [loginIdOrEmail, setLoginIdOrEmail] = useState('');
  const [password, setPassword] = useState('');
  const [showPassword, setShowPassword] = useState(false);
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);
  const [companyLogo, setCompanyLogo] = useState(null);
  const { login } = useAuth();
  const navigate = useNavigate();
  const location = useLocation();

  useEffect(() => {
    if (location.state?.message) {
      // Show success message if redirected from registration
      setTimeout(() => {
        setError('');
      }, 5000);
    }
    fetchCompanyLogo();
  }, [location]);

  const fetchCompanyLogo = async () => {
    try {
      const response = await api.get('/settings/company/logo');
      if (response.data?.logo_url && response.data.logo_url.trim() !== '') {
        setCompanyLogo(response.data.logo_url);
      }
    } catch (error) {
      console.error('Failed to fetch company logo:', error);
      setCompanyLogo(null);
    }
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setError('');
    setLoading(true);

    const result = await login(loginIdOrEmail, password);
    
    if (result.success) {
      // Check if password change is required
      if (result.requiresPasswordChange) {
        navigate('/change-password', { state: { firstTime: true } });
      } else {
        navigate('/dashboard');
      }
    } else {
      setError(result.error);
    }
    
    setLoading(false);
  };

  return (
    <div className="min-h-screen bg-gray-50 flex items-center justify-center px-4 py-6">
      <div className="w-full max-w-md">
        <div className="bg-white rounded-xl shadow-lg border-2 border-gray-200 overflow-hidden">
          <div className="px-8 py-6 border-b-2 border-gray-200">
            <div className="text-center">
              <div className="w-24 h-24 bg-gray-100 rounded-lg mx-auto mb-4 flex items-center justify-center border-2 border-gray-200">
                {companyLogo ? (
                  <img 
                    src={companyLogo} 
                    alt="Company Logo" 
                    className="w-full h-full object-contain rounded-lg"
                    onError={() => setCompanyLogo(null)}
                  />
                ) : (
                  <span className="text-gray-400 text-xs">App/Web Logo</span>
                )}
              </div>
              <h1 className="text-2xl font-bold mb-2" style={{ color: '#8200db' }}>Sign in Page</h1>
            </div>
          </div>

          <div className="px-8 py-6">
            {location.state?.message && (
              <div className="bg-green-50 border-2 border-green-200 text-green-700 px-4 py-3 rounded-lg mb-6">
                {location.state.message}
              </div>
            )}

            <form onSubmit={handleSubmit} className="space-y-6">
              {error && (
                <div className="bg-red-50 border-2 border-red-200 text-red-700 px-4 py-3 rounded-lg">
                  {error}
                </div>
              )}

              <div>
                <label htmlFor="loginIdOrEmail" className="block text-xs font-medium text-gray-700 mb-2">
                  Login ID
                </label>
                <input
                  id="loginIdOrEmail"
                  type="text"
                  value={loginIdOrEmail}
                  onChange={(e) => setLoginIdOrEmail(e.target.value)}
                  required
                  className="w-full px-4 py-2.5 text-sm border-2 border-gray-300 rounded-lg focus:border-[#8200db] focus:outline-none transition-colors"
                  placeholder="Enter Login ID or Email"
                />
                <p className="text-xs text-gray-500 mt-2">
                  The Login ID would be automatically generated by the system in the following format: 
                  [first two letters of the company's first and last name] [year of joining] [serial number of joining]
                  <br />
                  <span className="font-semibold">Example: WORKDHPAT20250001</span>
                </p>
                <p className="text-xs text-gray-500 mt-1 italic">
                  Password would be auto-generated for the first time by the system. They can login and change the system generated password.
                </p>
              </div>

              <div>
                <label htmlFor="password" className="block text-xs font-medium text-gray-700 mb-2">
                  Password
                </label>
                <div className="relative">
                  <input
                    id="password"
                    type={showPassword ? 'text' : 'password'}
                    value={password}
                    onChange={(e) => setPassword(e.target.value)}
                    required
                    className="w-full px-4 py-2.5 text-sm border-2 border-gray-300 rounded-lg focus:border-[#8200db] focus:outline-none transition-colors pr-10"
                    placeholder="Enter your password"
                  />
                  <button
                    type="button"
                    onClick={() => setShowPassword(!showPassword)}
                    className="absolute right-3 top-1/2 transform -translate-y-1/2 text-gray-500 hover:text-gray-700"
                  >
                    {showPassword ? (
                      <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13.875 18.825A10.05 10.05 0 0112 19c-4.478 0-8.268-2.943-9.543-7a9.97 9.97 0 011.563-3.029m5.858.908a3 3 0 114.243 4.243M9.878 9.878l4.242 4.242M9.88 9.88l-3.29-3.29m7.532 7.532l3.29 3.29M3 3l3.59 3.59m0 0A9.953 9.953 0 0112 5c4.478 0 8.268 2.943 9.543 7a10.025 10.025 0 01-4.132 5.411m0 0L21 21" />
                      </svg>
                    ) : (
                      <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z" />
                      </svg>
                    )}
                  </button>
                </div>
              </div>

              <button
                type="submit"
                disabled={loading}
                className="w-full text-white py-2.5 px-4 rounded-lg font-semibold shadow-md hover:shadow-lg transition-all disabled:opacity-50 disabled:cursor-not-allowed"
                style={{ backgroundColor: '#8200db' }}
              >
                {loading ? 'Logging in...' : 'SIGN IN'}
              </button>

              <div className="text-center">
                <Link to="/forgot-password" className="text-sm hover:underline" style={{ color: '#8200db' }}>
                  Send link to Reset Password?
                </Link>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Login;
